/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for palette gadget
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>

#include <proto/exec.h>
#include <proto/palette.h>
#include <assert.h>

/****************************************************************************/

struct Library *PaletteBase = NULL;
static struct Library *__PaletteBase;

/****************************************************************************/

void
palette_base_constructor (void)
{
  if (PaletteBase != NULL)
    {
      return;			/* Someone was quicker, e.g. an interface constructor */
    }
  __PaletteBase = PaletteBase =
    (struct Library *) OpenLibrary ("gadgets/palette.gadget", 51L);
  assert (PaletteBase != NULL);
}

__attribute__ ((section (".ctors.zzzz")))
     static void
       (*palette_base_constructor_ptr) (void) USED = palette_base_constructor;

/****************************************************************************/

     void palette_base_destructor (void)
{
  if (__PaletteBase)
    {
      CloseLibrary ((struct Library *) __PaletteBase);
    }
}

__attribute__ ((section (".dtors.zzzz")))
     static void
       (*palette_base_destructor_ptr) (void) USED = palette_base_destructor;

/****************************************************************************/
