/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for palette gadget
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>

#include <proto/exec.h>
#include <proto/palette.h>
#include <assert.h>

struct PaletteIFace *IPalette = NULL;
static struct Library *__PaletteBase;
static struct PaletteIFace *__IPalette;

/****************************************************************************/

extern struct Library *PaletteBase;

/****************************************************************************/

void
palette_main_constructor (void)
{
  if (PaletteBase == NULL)	/* Library base is NULL, we need to open it */
    {
      /* We were called before the base constructor.
       * This means we will be called _after_ the base destructor.
       * So we cant drop the interface _after_ closing the last library base,
       * we just open the library here which ensures that.
       */
      __PaletteBase = PaletteBase =
	(struct Library *) OpenLibrary ("gadgets/palette.gadget", 0L);
      assert (PaletteBase != NULL);
    }

  __IPalette = IPalette =
    (struct SYSVIFace *) GetInterface ((struct Library *) PaletteBase, "main",
				       1, NULL);
  assert (IPalette != NULL);
}

__attribute__ ((section (".ctors.zzzy")))
     static void
       (*palette_main_constructor_ptr) (void) USED = palette_main_constructor;

/****************************************************************************/

     void palette_main_destructor (void)
{
  if (__IPalette)
    {
      DropInterface ((struct Interface *) __IPalette);
    }
  if (__PaletteBase)
    {
      CloseLibrary ((struct Library *) __PaletteBase);
    }
}

__attribute__ ((section (".dtors.zzzy")))
     static void
       (*palette_main_destructor_ptr) (void) USED = palette_main_destructor;

/****************************************************************************/
